# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

altgpuvector_int <- function(n) {
    .Call(`_altgpu_altgpuvector_int`, n)
}

altgpuvector_real <- function(n) {
    .Call(`_altgpu_altgpuvector_real`, n)
}

